### ISSUE TITLE
Question: Cursor grabbing

### ISSUE THREAD

**Issue by nico281** [reppners/ngx-drag-drop#66]
Hi, how are you reppners?
Its possible to change the cursor to grabbing for example while grabbing a element?

cheers!!

**Comment by reppners** [comment]
Hi, thanks I'm good 👍 

I've put together a small example:
https://stackblitz.com/edit/ngx-drag-drop-issue-template-gxpspj

**Comment by nico281** [comment]
thanks for your reply. The question was regarding the default cursor while the item is dragging. But i think that is html5 native and you can't change it.

**Comment by kamentk** [comment]
Having the same issues. Is there any workaround to change the cursor for the whole life cycle of the dragging? It seems that the cursors are applied by the browsers as the DnD behaves in different ways in the both browsers.

**Comment by VitaliiHoncharenko** [comment]
any updates?

**Comment by reppners** [comment]
There are the css classes that are applied to the elements throughout the drag and drop lifecycle as showcased in the stackblitz above and documented in the API (https://github.com/reppners/ngx-drag-drop#api). This should enable to fully customize how the involved elements and the cursor looks like. What I've noticed though is that behaviour is glitchy.. it sometimes works, sometimes it doesn't and I think its related to timing and the drag image of the browser prevents the hit testing of CSS to apply the changed style after dragging starts. To workaround this the application could apply a style to the component or even the whole body on drag start and remove it on drag end to enable reliable global styling while dragging is in progress.

CSS also allows to use images, e.g.
```CSS
.custom {
  /* The second value here is a fallback. */
  cursor: url(images/my-cursor.png), auto;

  /* You may need coordinates to adjust the pointer
     for example, the custom cursor is circular and you want
     the middle to be where you click */
  cursor: url(target.svg) 15 15, move;
}
```

If further advice is needed, let me know and I'll reopen.
